name: express-restful-api
author: jahchuen
org: Tencent Cloud, Inc.
description: Build a serverless REST API application with tencent serverless SCF component
keywords: tencent, serverless, rest api, scf
license: MIT
src:
  src: ./
  exclude:
    - .env
    - '.git/**'
