org: serverless
app: express-restful-api
stage: dev
component: express
name: express-restful-api

inputs:
  src: ./
  functionName: ${name}
  region: ${env:REGION}
  runtime: Nodejs10.15
  timeout: 30
  apigatewayConf:
    enableCORS: true
    protocols:
      - http
      - https
